### PR TITLE
List all websites here

### PR DESCRIPTION
**Pull request by bepitulaz**
I don't think we need a database engine. Let's write all URLs here. We don't need scalable solution for now. Pretty sure a simple array find can do the job.

### CODE REVIEW

**Review by untungso — APPROVED** [review]
LGTM

**Comment by batara666** [comment]
this is so ineffective, here's the alternative:

```
frontend <-> backend <-> scrape from google.com, duckduckgo, yahoo, bing
```

**Comment by bepitulaz** [comment]
@batara666 That's too efficient for the alpha version 😂

**Comment by arya1109** [comment]
> 

self hosted server kampus

**Comment by batara666** [comment]
on stable 5.x.x version, we will run infinite scraper engine starting from [google.com/search?q=a](google.com/search?q=a), any link that are exist on the web will be visited, and the engine will also enumerate subdomain, so any internal service will be revealed (will also support shodan-like discoveries).

I assume the data will be over thousand of terabyte before 2024 and the data center will be served from Bukit Algoritma

**Comment by bepitulaz** [comment]
@batara666 I like the idea, but....how can we scrape Google if it is blocked? Still we have to input the data manually via "gotong royong".

**Comment by imrenagi** [comment]
LGTM

**Comment by batara666** [comment]
no problem @bepitulaz , I know a guy who sells proxy 😎

**Pull request merged**
